use_frameworks!
platform :ios, '9.3'

target 'SwiftDog_Example' do
  pod 'SwiftDog', :path => '../'


end

target 'SwiftDog_Tests' do
    pod 'SwiftDog', :path => '../'
    
    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
end
