use_frameworks!

target 'SwiftDog_Example' do
  pod 'SwiftDog', :path => '../'

  target 'SwiftDog_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
